### ISSUE TITLE
installataion error

### ISSUE THREAD

**Issue by Ramone31** [kelektiv/node.bcrypt.js#1019]
when i try to install bcrypt version 5 or below ,it not install for node js version 14.it show error like this

node-pre-gyp WARN Pre-built binaries not installable for bcrypt@5.1.1 and node@10.19.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error ENOENT: no such file or directory, mkdir 
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '//node_modules/bcrypt/build'
gyp ERR! System Linux 5.4.0-56-generic
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "configure" "--fallback-to-build" "--module=//node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=//node_modules/bcrypt/lib/binding/napi-v3" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
gyp ERR! cwd //node_modules/bcrypt
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/bin/node-gyp configure --fallback-to-build --module=//node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node --module_name=bcrypt_lib --module_path=//node_modules/bcrypt/lib/binding/napi-v3 --napi_version=5 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
node-pre-gyp ERR! stack     at ChildProcess.cmd.on (//node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 5.4.0-56-generic
node-pre-gyp ERR! command "/usr/bin/node" "//node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd //node_modules/bcrypt
node-pre-gyp ERR! node -v v10.19.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.11
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/bin/node-gyp configure --fallback-to-build --module=//node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node --module_name=bcrypt_lib --module_path=//node_modules/bcrypt/lib/binding/napi-v3 --napi_version=5 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm WARN argus_sv2@1.0.0 No description
npm WARN argus_sv2@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@5.1.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@5.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2024-01-02T08_19_53_217Z-debug.log

**Comment by De-Hype** [comment]
Currently using Node version 20.9 and I had this issue.
Thought it was just an issue with my computer.

**Comment by Ramone31** [comment]
not a PC problem i updated node js version it works but i use node js version 14 it does not work

**Comment by Owez** [comment]
Yeah mine fails too, bcrypt issue

**Comment by AnchalDevBytes** [comment]
![Screenshot from 2024-03-07 16-22-04](https://github.com/kelektiv/node.bcrypt.js/assets/126651793/d50d7481-5a64-4f4c-8c15-2519da2ac0e4)


am also faciing the same issue, I have ```Ubuntu 20.04 LTS``` and  ```Node.js 20.11.1```  and   ```npm 10.2.4```

**Comment by AnchalDevBytes** [comment]
> ![Screenshot from 2024-03-07 16-22-04](https://private-user-images.githubusercontent.com/126651793/310864034-d50d7481-5a64-4f4c-8c15-2519da2ac0e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MTIxOTUsIm5iZiI6MTcwOTgxMTg5NSwicGF0aCI6Ii8xMjY2NTE3OTMvMzEwODY0MDM0LWQ1MGQ3NDgxLTVhNjQtNGY0Yy04YzE1LTI1MTlkYTJhYzBlNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QxMTQ0NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNWRkMTg5OTA0ZTkwZjA2NjJhNGQ2ZWRmNjRjZTY2MTYzN2U2YmNhNjNlYjE0MmRlYTI0Y2JlNWJiZjEzZjdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tmRDGH52rTRrR3EYu2nha6KBRaEWqridLHyteXNTT4A)
> 
> am also faciing the same issue, I have `Ubuntu 20.04 LTS` and `Node.js 20.11.1` and `npm 10.2.4`

I tried installing ```sudo npm install -g node-gyp``` and then retried to install bcrypt, still it didn't worked.

**Comment by RussellHaley** [comment]
> > ![Screenshot from 2024-03-07 16-22-04](https://private-user-images.githubusercontent.com/126651793/310864034-d50d7481-5a64-4f4c-8c15-2519da2ac0e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MTIxOTUsIm5iZiI6MTcwOTgxMTg5NSwicGF0aCI6Ii8xMjY2NTE3OTMvMzEwODY0MDM0LWQ1MGQ3NDgxLTVhNjQtNGY0Yy04YzE1LTI1MTlkYTJhYzBlNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QxMTQ0NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNWRkMTg5OTA0ZTkwZjA2NjJhNGQ2ZWRmNjRjZTY2MTYzN2U2YmNhNjNlYjE0MmRlYTI0Y2JlNWJiZjEzZjdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tmRDGH52rTRrR3EYu2nha6KBRaEWqridLHyteXNTT4A)
> > am also faciing the same issue, I have `Ubuntu 20.04 LTS` and `Node.js 20.11.1` and `npm 10.2.4`
> 
> I tried installing `sudo npm install -g node-gyp` and then retried to install bcrypt, still it didn't worked.

Can report the same on Ubuntu 22 with node 20.

**Comment by RussellHaley** [comment]
I've been able to work around the issue by cloning this repo and building and installing locally:

```
mkdir ~/git && cd ~/git
git clone https://github.com/kelektiv/node.bcrypt.js.git
cd node.bcrypt.js
make
cd ~/myproject
npm install ~/git/node.bcrypt.js
```
