### ISSUE TITLE
Error loading bindings file, sometimes

### ISSUE THREAD

**Issue by mjackson** [kelektiv/node.bcrypt.js#171]
I'm getting the following error pretty consistently after a fresh `npm install`: 

```
Error: Could not load the bindings file. Tried:
 → /vagrant/node_modules/bcrypt/build/bcrypt_lib.node
 → /vagrant/node_modules/bcrypt/build/Debug/bcrypt_lib.node
 → /vagrant/node_modules/bcrypt/build/Release/bcrypt_lib.node
 → /vagrant/node_modules/bcrypt/out/Debug/bcrypt_lib.node
 → /vagrant/node_modules/bcrypt/Debug/bcrypt_lib.node
 → /vagrant/node_modules/bcrypt/out/Release/bcrypt_lib.node
 → /vagrant/node_modules/bcrypt/Release/bcrypt_lib.node
 → /vagrant/node_modules/bcrypt/build/default/bcrypt_lib.node
 → /vagrant/node_modules/bcrypt/compiled/0.10.6/linux/x64/bcrypt_lib.node
    at bindings (/vagrant/node_modules/bcrypt/node_modules/bindings/bindings.js:84:13)
    at Object.<anonymous> (/vagrant/node_modules/bcrypt/bcrypt.js:1:97)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/vagrant/lib/utils.js:4:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.utils (/vagrant/lib/index.js:14:12)
    at Object.<anonymous> (/vagrant/spec/app/presence-spec.js:36:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /vagrant/node_modules/mocha/lib/mocha.js:152:27
    at Array.forEach (native)
    at Mocha.loadFiles (/vagrant/node_modules/mocha/lib/mocha.js:149:14)
    at Mocha.run (/vagrant/node_modules/mocha/lib/mocha.js:305:31)
    at Object.<anonymous> (/vagrant/node_modules/mocha/bin/_mocha:327:7)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
vagrant@dev:/vagrant$ npm uninstall bcrypt
vagrant@dev:/vagrant$ npm install bcrypt
npm http GET https://registry.npmjs.org/bcrypt
npm http 304 https://registry.npmjs.org/bcrypt
npm http GET https://registry.npmjs.org/bindings/1.0.0
npm http 304 https://registry.npmjs.org/bindings/1.0.0

> bcrypt@0.7.6 install /vagrant/node_modules/bcrypt
> node-gyp rebuild

make: Entering directory `/vagrant/node_modules/bcrypt/build'
make: Warning: File `bcrypt_lib.target.mk' has modification time 0.029 s in the future
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
  SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
  SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node: Finished
  COPY Release/bcrypt_lib.node
make: warning:  Clock skew detected.  Your build may be incomplete.
make: Leaving directory `/vagrant/node_modules/bcrypt/build'
bcrypt@0.7.6 node_modules/bcrypt
└── bindings@1.0.0
```

In order to fix the error (on my Vagrant box) I need to `npm uninstall bcrypt` and then `npm install bcrypt` again, which fixes the error. This leads me to believe that the bcrypt build is somehow getting corrupted when I install it together with the other packages that I have installed, but is fine when I install it all by itself.

I'm not sure if this will help at all, but here is a log of the output from `npm install` when bcrypt fails to build properly:

```
$ npm install
npm http GET https://registry.npmjs.org/then-redis
npm http GET https://registry.npmjs.org/when
npm http GET https://registry.npmjs.org/oauth
npm http GET https://registry.npmjs.org/handlebars
npm http GET https://registry.npmjs.org/mocha-as-promised
npm http GET https://registry.npmjs.org/then-couchdb
npm http GET https://registry.npmjs.org/bcrypt
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/follow
npm http GET https://github.com/hum/twitter-text-js/tarball/master
npm http GET https://registry.npmjs.org/coffee-resque/0.1.8
npm http GET https://registry.npmjs.org/mach
npm http GET https://registry.npmjs.org/imap
npm http 304 https://registry.npmjs.org/when
npm http 304 https://registry.npmjs.org/handlebars
npm http 304 https://registry.npmjs.org/then-redis
npm http 304 https://registry.npmjs.org/oauth
npm http 304 https://registry.npmjs.org/mocha-as-promised
npm http 304 https://registry.npmjs.org/then-couchdb
npm http 304 https://registry.npmjs.org/bcrypt
npm http 304 https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/follow
npm http 304 https://registry.npmjs.org/coffee-resque/0.1.8
npm http 304 https://registry.npmjs.org/mach
npm http 304 https://registry.npmjs.org/imap
npm http 200 https://github.com/hum/twitter-text-js/tarball/master
npm http GET https://registry.npmjs.org/redis
npm http GET https://registry.npmjs.org/mocha
npm http 304 https://registry.npmjs.org/redis
npm http 304 https://registry.npmjs.org/mocha
npm http GET https://registry.npmjs.org/bindings/1.0.0
npm http GET https://registry.npmjs.org/hiredis/0.1.15
npm http 304 https://registry.npmjs.org/bindings/1.0.0
npm http 304 https://registry.npmjs.org/hiredis/0.1.15
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/utf7/1.0.0
npm http 304 https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/utf7/1.0.0
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/uglify-js
npm http 304 https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/uglify-js
npm http GET https://registry.npmjs.org/wordwrap
npm http GET https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/strftime/0.5.0
npm http GET https://registry.npmjs.org/mime/1.2.9
npm http 304 https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/mime/1.2.9
npm http 304 https://registry.npmjs.org/strftime/0.5.0
npm http GET https://registry.npmjs.org/ms/0.3.0
npm http GET https://registry.npmjs.org/glob/3.2.1
npm http GET https://registry.npmjs.org/commander/0.6.1
npm http GET https://registry.npmjs.org/growl
npm http GET https://registry.npmjs.org/jade/0.26.3
npm http GET https://registry.npmjs.org/diff/1.0.2
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/mkdirp/0.3.5
npm http 304 https://registry.npmjs.org/ms/0.3.0
npm http 304 https://registry.npmjs.org/growl
npm http 304 https://registry.npmjs.org/jade/0.26.3
npm http 304 https://registry.npmjs.org/diff/1.0.2
npm http 304 https://registry.npmjs.org/commander/0.6.1
npm http 304 https://registry.npmjs.org/glob/3.2.1

> hiredis@0.1.15 install /vagrant/node_modules/then-redis/node_modules/hiredis
> node-gyp rebuild

npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/mkdirp/0.3.5
npm WARN package.json jade@0.26.3 No README.md file found!
npm http GET https://registry.npmjs.org/node-uuid
npm http GET https://registry.npmjs.org/hawk
npm http GET https://registry.npmjs.org/cookie-jar
npm http GET https://registry.npmjs.org/aws-sign
npm http GET https://registry.npmjs.org/oauth-sign
npm http GET https://registry.npmjs.org/forever-agent
npm http GET https://registry.npmjs.org/tunnel-agent
npm http GET https://registry.npmjs.org/json-stringify-safe
npm http GET https://registry.npmjs.org/qs
npm http GET https://registry.npmjs.org/form-data
npm http GET https://registry.npmjs.org/mime
npm http 304 https://registry.npmjs.org/hawk
npm http 304 https://registry.npmjs.org/aws-sign
npm http 304 https://registry.npmjs.org/cookie-jar
npm http 304 https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/oauth-sign
npm http 304 https://registry.npmjs.org/tunnel-agent
npm http 304 https://registry.npmjs.org/forever-agent
npm http 304 https://registry.npmjs.org/json-stringify-safe
npm http 304 https://registry.npmjs.org/qs
npm http 304 https://registry.npmjs.org/form-data
npm http 304 https://registry.npmjs.org/mime
npm WARN package.json aws-sign@0.2.0 No README.md file found!
npm WARN package.json cookie-jar@0.2.0 No README.md file found!
npm WARN package.json oauth-sign@0.2.0 No README.md file found!
npm WARN package.json tunnel-agent@0.2.0 No README.md file found!
npm WARN package.json forever-agent@0.2.0 No README.md file found!
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.6","npm":"1.2.18"})
make: Entering directory `/vagrant/node_modules/then-redis/node_modules/hiredis/build'
  CC(target) Release/obj.target/hiredis/deps/hiredis/hiredis.o
npm http GET https://registry.npmjs.org/combined-stream
  CC(target) Release/obj.target/hiredis/deps/hiredis/net.o
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/source-map
npm http GET https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/combined-stream
npm http 304 https://registry.npmjs.org/async
  CC(target) Release/obj.target/hiredis/deps/hiredis/sds.o
npm http 304 https://registry.npmjs.org/source-map
npm http 304 https://registry.npmjs.org/async
  CC(target) Release/obj.target/hiredis/deps/hiredis/async.o
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/inherits
  AR(target) Release/obj.target/deps/hiredis.a
  COPY Release/hiredis.a
  CXX(target) Release/obj.target/hiredis/src/hiredis.o
npm http GET https://registry.npmjs.org/delayed-stream/0.0.5
npm http GET https://registry.npmjs.org/cryptiles
npm http GET https://registry.npmjs.org/hoek
npm http GET https://registry.npmjs.org/sntp
npm http GET https://registry.npmjs.org/boom
npm http GET https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/sigmund
npm http 304 https://registry.npmjs.org/delayed-stream/0.0.5
npm http 304 https://registry.npmjs.org/lru-cache
  CXX(target) Release/obj.target/hiredis/src/reader.o
npm http 304 https://registry.npmjs.org/sigmund
npm http GET https://registry.npmjs.org/mkdirp/0.3.0
npm http 304 https://registry.npmjs.org/cryptiles
npm http 304 https://registry.npmjs.org/hoek
npm http 304 https://registry.npmjs.org/sntp
npm http 304 https://registry.npmjs.org/boom
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.6","npm":"1.2.18"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.6","npm":"1.2.18"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.6","npm":"1.2.18"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.6","npm":"1.2.18"})
npm http 304 https://registry.npmjs.org/mkdirp/0.3.0
  SOLINK_MODULE(target) Release/obj.target/hiredis.node
npm http GET https://registry.npmjs.org/amdefine
npm http 304 https://registry.npmjs.org/amdefine
  SOLINK_MODULE(target) Release/obj.target/hiredis.node: Finished
  COPY Release/hiredis.node
make: Leaving directory `/vagrant/node_modules/then-redis/node_modules/hiredis/build'
oauth@0.9.10 node_modules/oauth

underscore@1.4.4 node_modules/underscore

when@2.1.1 node_modules/when

bcrypt@0.7.6 node_modules/bcrypt
└── bindings@1.0.0

then-couchdb@0.3.9 node_modules/then-couchdb
└── when@2.0.1

imap@0.7.12 node_modules/imap
└── utf7@1.0.0

coffee-resque@0.1.8 node_modules/coffee-resque
└── redis@0.8.4

mach@0.4.3 node_modules/mach
├── strftime@0.5.0
├── mime@1.2.9
└── when@2.0.1

twitter-text@1.6.1 node_modules/twitter-text

then-redis@0.3.8 node_modules/then-redis
├── when@2.0.1
└── hiredis@0.1.15 (bindings@1.1.0)

mocha@1.11.0 node_modules/mocha
├── growl@1.7.0
├── debug@0.7.2
├── commander@0.6.1
├── diff@1.0.2
├── mkdirp@0.3.5
├── ms@0.3.0
├── glob@3.2.1 (inherits@1.0.0, graceful-fs@1.2.2, minimatch@0.2.12)
└── jade@0.26.3 (mkdirp@0.3.0)

mocha-as-promised@1.3.0 node_modules/mocha-as-promised

handlebars@1.0.12 node_modules/handlebars
├── optimist@0.3.7 (wordwrap@0.0.2)
└── uglify-js@2.3.6 (async@0.2.9, source-map@0.1.25)

follow@0.9.0 node_modules/follow
└── request@2.16.6 (forever-agent@0.2.0, aws-sign@0.2.0, tunnel-agent@0.2.0, oauth-sign@0.2.0, json-stringify-safe@3.0.0, cookie-jar@0.2.0, node-uuid@1.4.0, mime@1.2.9, qs@0.5.6, form-data@0.0.10, hawk@0.10.2)
```

AFAICT the only other build going on is hiredis. Could this be conflicting somehow?

**Comment by totophe** [comment]
Could come from here: http://stackoverflow.com/questions/15809611/bcrypt-invalid-elf-header-when-running-node-app

**Comment by KrishnaPG** [comment]
getting the same issue with latest nodejs and fresh install on ubuntu LTS 14.04:
````
Error: Could not load the bindings file. Tried:
 → /server/npm/npm-bcrypt/node_modules/bcrypt/build/bcrypt_lib.node
 → /server/npm/npm-bcrypt/node_modules/bcrypt/build/Debug/bcrypt_lib.node
 → /server/npm/npm-bcrypt/node_modules/bcrypt/build/Release/bcrypt_lib.node
 → /server/npm/npm-bcrypt/node_modules/bcrypt/out/Debug/bcrypt_lib.node
 → /server/npm/npm-bcrypt/node_modules/bcrypt/Debug/bcrypt_lib.node
 → /server/npm/npm-bcrypt/node_modules/bcrypt/out/Release/bcrypt_lib.node
 →/server/npm/npm-bcrypt/node_modules/bcrypt/Release/bcrypt_lib.node
 → /server/npm/npm-bcrypt/node_modules/bcrypt/build/default/bcrypt_lib.node
 → /server/npm/npm-bcrypt/node_modules/bcrypt/compiled/0.12.7/linux/x64/bcrypt_lib.node
    at bindings (/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:84:13)
    at Object.<anonymous> (/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.Npm.require (/server/boot.js:142:18)
    at packages/npm-bcrypt/wrapper.js:1:1
````
