### ISSUE TITLE
problem running on Amazon Linux with gcc 6.3 

### ISSUE THREAD

**Issue by lakamsani** [kelektiv/node.bcrypt.js#475]
Hi, we are trying the 1.0.2 version of bcrypt (previously using bcrypt-nodejs) with our node.js app (node 6.9.3)

It works fine on MacOS and ubuntu 14.x but on an Amazon Linux with gcc 6.3.0 we get this error and node is unable to start up. 

```bash
 Error: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/ec2-user/myapp-node/node_modules/bcrypt/lib/binding/bcrypt_lib.node)
1|myapp   |     at Error (native)
1|myapp   |     at Object.Module._extensions..node (module.js:597:18)
1|myapp   |     at Module.load (module.js:487:32)
1|myapp   |     at tryModuleLoad (module.js:446:12)
1|myapp   |     at Function.Module._load (module.js:438:3)
1|myapp   |     at Function.<anonymous> (/home/ec2-user/tools/node-v6.9.3-linux-x64/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
1|myapp   |     at Function.cls_wrapMethod [as _load] (/home/ec2-user/myapp-node/node_modules/newrelic/lib/shimmer.js:246:38)
1|myapp   |     at Module.require (module.js:497:17)
1|myapp   |     at require (internal/module.js:20:19)
1|myapp   |     at Object.<anonymous> (/home/ec2-user/myapp-node/node_modules/bcrypt/bcrypt.js:6:16)
1|myapp   |     at Module._compile (module.js:570:32)
1|myapp   |     at Object.Module._extensions..js (module.js:579:10)
1|myapp   |     at Module.load (module.js:487:32)
1|myapp   |     at tryModuleLoad (module.js:446:12)
1|myapp   |     at Function.Module._load (module.js:438:3)
1|myapp   |     at Function.<anonymous> (/home/ec2-user/tools/node-v6.9.3-linux-x64/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
1|myapp   |     at Function.cls_wrapMethod [as _load] (/home/ec2-user/myapp-node/node_modules/newrelic/lib/shimmer.js:246:38)
1|myapp   |     at Module.require (module.js:497:17)
1|myapp   |     at require (internal/module.js:20:19)
1|myapp   |     at Object.<anonymous> (/home/ec2-user/myapp-node/models/User.js:1:76)
1|myapp   |     at Module._compile (module.js:570:32)
1|myapp   |     at Object.Module._extensions..js (module.js:579:10)
1|myapp   |     at Module.load (module.js:487:32)
1|myapp   |     at tryModuleLoad (module.js:446:12)
1|myapp   |     at Function.Module._load (module.js:438:3)
1|myapp   |     at Function.<anonymous> (/home/ec2-user/tools/node-v6.9.3-linux-x64/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
1|myapp   |     at Function.cls_wrapMethod [as _load] (/home/ec2-user/myapp-node/node_modules/newrelic/lib/shimmer.js:246:38)
1|myapp   |     at Module.require (module.js:497:17)
PM2        | App name:myapp id:1 disconnected
```

Amazon Linux version: Linux ip-172-31-46-113 4.4.39-34.54.amzn1.x86_64 #1 SMP Fri Dec 30 19:11:28 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

This Amazon Linux (2016.09) VM does not have 32-bit libs. Are those needed?

```bash
 strings /usr/lib64/libstdc++.so.6  | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

But the output pretty much the same on ubuntu 14 and it works there. here is the output on ubuntu 14

```bash
strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6  | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

Output of npm install on Amazon Linux is this:

```bash
> bcrypt@1.0.2 install /home/ec2-user/onkore-node/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v48-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.2 and node@6.9.3 (node-v48 ABI) (falling back to source compile with node-gyp)
make: Entering directory `/home/ec2-user/myapp-node/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
  SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
  COPY Release/bcrypt_lib.node
  COPY /home/ec2-user/myapp-node/node_modules/bcrypt/lib/binding/bcrypt_lib.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Leaving directory `/home/ec2-user/myapp-node/node_modules/bcrypt/build'

```

On Amazon Linux, ldd says this:
```bash
ldd  /home/ec2-user/myapp-node/node_modules/bcrypt/lib/binding/bcrypt_lib.node
/home/ec2-user/myapp-node/node_modules/bcrypt/lib/binding/bcrypt_lib.node: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/ec2-user/myapp-node/node_modules/bcrypt/lib/binding/bcrypt_lib.node)
	linux-vdso.so.1 =>  (0x00007ffd214ef000)
	libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007fd915e15000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fd915b13000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fd9158fc000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fd9156e0000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fd91531e000)
	/lib64/ld-linux-x86-64.so.2 (0x0000562edc721000)
```

On Ubuntu14 ldd says this. Note no complaint about missing GLIBCXX_3.4.21
```bash
ldd /home/ubuntu/myapp-node/node_modules/bcrypt/lib/binding/bcrypt_lib.node
	linux-vdso.so.1 =>  (0x00007f3d7c437000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f3d7bf1d000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3d7bcff000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3d7b939000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f3d7b633000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f3d7c439000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f3d7b41d000)
```

**Comment by lakamsani** [comment]
```bash 

% node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@6.9.3 | linux | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/home/ec2-user/tools/node-v6.9.3-linux-x64/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ec2-user/onkore-node/node_modules/bcrypt/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ec2-user/tools/node-v6.9.3-linux-x64/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ec2-user/.node-gyp/6.9.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/ec2-user/.node-gyp/6.9.3',
gyp info spawn args   '-Dnode_gyp_dir=/home/ec2-user/tools/node-v6.9.3-linux-x64/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/ec2-user/onkore-node/node_modules/bcrypt',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/ec2-user/tools/node-v6.9.3-linux-x64/lib/node_modules/node-gyp/lib/configure.js:308:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.39-34.54.amzn1.x86_64
gyp ERR! command "/home/ec2-user/tools/node-v6.9.3-linux-x64/bin/node" "/home/ec2-user/bin/node-gyp" "configure"
gyp ERR! cwd /home/ec2-user/onkore-node/node_modules/bcrypt
gyp ERR! node -v v6.9.3
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
```

**Comment by lakamsani** [comment]
problem was resolved by doing this:
1. set  LD_LIBRARY_PATH  ensure that /usr/local/lib64 is before other directories. That is where my locally compiled gcc 6.3 was installed.
2. npm install to rebuild bcrypt with those libs.
