### ISSUE TITLE
Not able to use bcrypt.

### ISSUE THREAD

**Issue by Anshdesire** [kelektiv/node.bcrypt.js#482]
Using Azure app node.

On azure server this error comes while on my local machine it works.

is there any issue on bcrypt or on azure app node?

Not able to use bcrypt

\\?\D:\home\site\wwwroot\node_modules\bcrypt\build\Release\bcrypt_lib.node
    at Error (native)
    at Object.Module._extensions..node (module.js:460:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at bindings (D:\home\site\wwwroot\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\bcrypt\bcrypt.js:3:35)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
Application has thrown an uncaught exception and is terminated:
Error: %1 is not a valid Win32 application.

\\?\D:\home\site\wwwroot\node_modules\bcrypt\build\Release\bcrypt_lib.node
    at Error (native)
    at Object.Module._extensions..node (module.js:460:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at bindings (D:\home\site\wwwroot\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\bcrypt\bcrypt.js:3:35)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)

**Comment by Agathver** [comment]
@Anshdesire 
Please add some more information. What it appears here is you are missing WinSDK, Python and other pre-requisites.
