### ISSUE TITLE
Electron Throw Error on loading of Bcrypt

### ISSUE THREAD

**Issue by biomade** [kelektiv/node.bcrypt.js#495]
I am writing a small Electron app to generate an encrypted password and when I load the page with the require('bcrypt') it throws an error.

here is the error trace from the console:
`Uncaught Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\laurie\Documents\GitHub\BcryptDesktopTool\node_modules\bcrypt\lib\binding\bcrypt_lib.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\laurie\Documents\GitHub\BcryptDesktopTool\node_modules\bcrypt\bcrypt.js:6:16)
    at Object.<anonymous> (C:\Users\laurie\Documents\GitHub\BcryptDesktopTool\node_modules\bcrypt\bcrypt.js:206:3)`

**Comment by kylevandenelsen** [comment]
I am experiencing the same error, have you figured this out yet?

**Comment by biomade** [comment]
It has been a while but I did get it working but I don't remember what I did.  Here is a link to repo; download it and compare it to yours  https://github.com/biomade/BcryptDesktopTool

**Comment by kylevandenelsen** [comment]
Okay, I am now using [https://www.npmjs.com/package/bcrypt-nodejs](https://www.npmjs.com/package/bcrypt-nodejs) which is working like a charm. Weird that this one is not working for me.

**Comment by kailniris** [comment]
For nw.js and electron You have to rebuild the binaries cuz the ABI is different. 
https://github.com/nwjs/nw-gyp
https://github.com/electron/electron/issues/2330

**Comment by Agathver** [comment]
Electron has a different ABI, therefore you have to rebuild the module: 
`npm rebuild bcrypt --build-from-source --runtime=electron`
