### ISSUE TITLE
Build Failed on Heroku 404

### ISSUE THREAD

**Issue by abarcenas29** [kelektiv/node.bcrypt.js#517]
```
       error /tmp/build_3b2f2f8ae8986ee9e7462a9e71789031/node_modules/bcrypt: Command failed.
       Exit code: 1
       Command: sh
       Arguments: -c node-pre-gyp install --fallback-to-build
       Directory: /tmp/build_3b2f2f8ae8986ee9e7462a9e71789031/node_modules/bcrypt
       Output:
       node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v57-linux-x64.tar.gz
       node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.2 and node@8.1.1 (node-v57 ABI) (falling back to source compile with node-gyp)
       gyp ERR! configure error
       gyp ERR! stack Error: 404 response downloading https://nodejs.org/download//v8.1.1/node-v8.1.1-headers.tar.gz
       gyp ERR! stack     at Request.<anonymous> (/tmp/build_3b2f2f8ae8986ee9e7462a9e71789031/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:210:14)
       gyp ERR! stack     at emitOne (events.js:120:20)
       gyp ERR! stack     at Request.emit (events.js:210:7)
       gyp ERR! stack     at Request.onRequestResponse (/tmp/build_3b2f2f8ae8986ee9e7462a9e71789031/.heroku/node/lib/node_modules/npm/node_modules/request/request.js:1074:10)
       gyp ERR! stack     at emitOne (events.js:115:13)
       gyp ERR! stack     at ClientRequest.emit (events.js:210:7)
       gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:564:21)
       gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
       gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:453:20)
       gyp ERR! stack     at emitOne (events.js:115:13)
       gyp ERR! System Linux 3.13.0-112-generic
       gyp ERR! command "/tmp/build_3b2f2f8ae8986ee9e7462a9e71789031/.heroku/node/bin/node" "/tmp/build_3b2f2f8ae8986ee9e7462a9e71789031/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/tmp/build_3b2f2f8ae8986ee9e7462a9e71789031/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/tmp/build_3b2f2f8ae8986ee9e7462a9e71789031/node_modules/bcrypt/lib/binding"
       gyp ERR! cwd /tmp/build_3b2f2f8ae8986ee9e7462a9e71789031/node_modules/bcrypt
       gyp ERR! node -v v8.1.1
       gyp ERR! node-gyp -v v3.6.2
       gyp ERR! not ok
       node-pre-gyp ERR! build error
       node-pre-gyp ERR! stack Error: Failed to execute '/tmp/build_3b2f2f8ae8986ee9e7462a9e71789031/.heroku/node/bin/node /tmp/build_3b2f2f8ae8986ee9e7462a9e71789031/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/tmp/build_3b2f2f8ae8986ee9e7462a9e71789031/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/tmp/build_3b2f2f8ae8986ee9e7462a9e71789031/node_modules/bcrypt/lib/binding' (1)
       node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/tmp/build_3b2f2f8ae8986ee9e7462a9e71789031/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
       node-pre-gyp ERR! stack     at emitTwo (events.js:125:13)
       node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
       node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:897:16)
       node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
       node-pre-gyp ERR! System Linux 3.13.0-112-generic
       node-pre-gyp ERR! command "/tmp/build_3b2f2f8ae8986ee9e7462a9e71789031/.heroku/node/bin/node" "/tmp/build_3b2f2f8ae8986ee9e7462a9e71789031/node_modules/bcrypt/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
       node-pre-gyp ERR! cwd /tmp/build_3b2f2f8ae8986ee9e7462a9e71789031/node_modules/bcrypt
       node-pre-gyp ERR! node -v v8.1.1
       node-pre-gyp ERR! node-pre-gyp -v v0.6.32
       node-pre-gyp ERR! not ok
       Failed to execute '/tmp/build_3b2f2f8ae8986ee9e7462a9e71789031/.heroku/node/bin/node /tmp/build_3b2f2f8ae8986ee9e7462a9e71789031/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/tmp/build_3b2f2f8ae8986ee9e7462a9e71789031/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/tmp/build_3b2f2f8ae8986ee9e7462a9e71789031/node_modules/bcrypt/lib/binding' (1)
       info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

basically: https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v57-linux-x64.tar.gz is gone.

Kindly advise.

**Comment by tobiasmuecksch** [comment]
Maybe you can fix this error:
https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions


Make sure that the following packages are present and working: `python` `g++` and `make`

**Comment by abarcenas29** [comment]
I can't use it. Heroku doesn't provide the apt-get access.

**Comment by tobiasmuecksch** [comment]
@abarcenas29 What version of node do you use?

**Comment by abarcenas29** [comment]
8.1.1

**Comment by tobiasmuecksch** [comment]
Please try to use 7.10.0

**Comment by tobiasmuecksch** [comment]
I guess the nodeJS people have to fix some build issues in 8.x

**Comment by tobiasmuecksch** [comment]
For me downgrading to 7.x worked

**Comment by abarcenas29** [comment]
Thanks!

**Comment by ekpangmichael** [comment]
I used node engine 
```
"engines": {
  "node": "8.11.1"
  },
```
It works for me
