### ISSUE TITLE
Installation without internet access

### ISSUE THREAD

**Issue by Jcambass** [kelektiv/node.bcrypt.js#541]
Hi there I'm trying to install bcrypt in an env without any internet access.
I've installed the Basis-Devel pattern fpr SLES 12.2 (SLES equivalent of build-essentials) and I'm using node 7.8.0 and yarn 0.27.5.

# What went wrong?

Installing bcrypt with yarn leads to an error. I'm not really sure what the real problem is thoe. Are header files missing and can I pass download them manually and put them somewhere. I already tried the --nodedir option, once pointed to the downloaded headers and once to the normal node installation.

# What did you expect to happen?

Compile bcrypt local without the need to download any external files or providing a possibility to manually download the required files and specifiy a directory/ providing instructions where to put them.

# Which version of nodejs and OS?

OS: Suse Linux Enterprise Server 12 Patch 2. 
Yarn: 0.27.5
node: 7.8.0

# The complete output:

```

Exit code: 1 
Command: sh 
Arguments: -c node-pre-gyp install --fallback-to-build 
Directory: /opt/PROJECT_NAME/MS-NAME/node_modules/bcrypt 
Output: 
node-pre-gyp info it worked if it ends with ok 
node-pre-gyp info using node-pre-gyp@0.6.36 
node-pre-gyp info using node@7.8.0 | linux | x64 
node-pre-gyp info check checked for "/opt/PROJECT_NAME/MS-NAME/node_modules/bcrypt/lib/binding/bcrypt_lib.node" (not found) 
node-pre-gyp http GET https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v51-linux-x64.tar.gz 
node-pre-gyp ERR! Tried to download(undefined): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v51-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.3 and node@7.8.0 (node-v51 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http getaddrinfo ENOTFOUND github.com github.com:443 
gyp info it worked if it ends with ok 
gyp info using node-gyp@3.5.0 
gyp info using node@7.8.0 | linux | x64 
gyp info ok 
gyp info it worked if it ends with ok 
gyp info using node-gyp@3.5.0 
gyp info using node@7.8.0 | linux | x64 
gyp http GET https://nodejs.org/download/release/v7.8.0/node-v7.8.0-headers.tar.gz 
gyp WARN install got an error, rolling back install 
gyp ERR! configure error 
gyp ERR! stack Error: This is most likely not a problem with node-gyp or the package itself and 
gyp ERR! stack is related to network connectivity. In most cases you are behind a proxy or have bad 
gyp ERR! stack network settings. 
gyp ERR! stack     at Request.<anonymous> (/opt/node-v7.8.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:193:21) 
gyp ERR! stack     at emitOne (events.js:96:13) 
gyp ERR! stack     at Request.emit (events.js:191:7) 
gyp ERR! stack     at Request.onRequestError (/opt/node-v7.8.0-linux-x64/lib/node_modules/npm/node_modules/request/request.js:845:8) 
gyp ERR! stack     at emitOne (events.js:96:13) 
gyp ERR! stack     at ClientRequest.emit (events.js:191:7) 
gyp ERR! stack     at TLSSocket.socketErrorListener (_http_client.js:358:9) 
gyp ERR! stack     at emitOne (events.js:96:13) 
gyp ERR! stack     at TLSSocket.emit (events.js:191:7) 
gyp ERR! stack     at connectErrorNT (net.js:1031:8) 
gyp ERR! System Linux 4.4.49-92.14-default 
gyp ERR! command "/opt/node-v7.8.0-linux-x64/bin/node" "/opt/node-v7.8.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/opt/PROJECT_NAME/MS-NAME/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/opt/PROJECT_NAME/MS-NAME/node_modules/bcrypt/lib/binding" 
gyp ERR! cwd /opt/PROJECT_NAME/MS-NAME/node_modules/bcrypt 
gyp ERR! node -v v7.8.0 
gyp ERR! node-gyp -v v3.5.0 
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/opt/node-v7.8.0-linux-x64/bin/node /opt/node-v7.8.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/opt/PROJECT_NAME/MS-NAME/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/opt/PROJECT_NAME/MS-NAME/node_modules/bcrypt/lib/binding' (1) 
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/opt/PROJECT_NAME/MS-NAME/node_modules/node-pre-gyp/lib/util/compile.js:83:29) 
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13) 
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:194:7) 
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:899:16) 
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5) 
node-pre-gyp ERR! System Linux 4.4.49-92.14-default 
node-pre-gyp ERR! command "/opt/node-v7.8.0-linux-x64/bin/node" "/opt/PROJECT_NAME/MS-NAME/node_modules/bcrypt/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" 
node-pre-gyp ERR! cwd /opt/PROJECT_NAME/MS-NAME/node_modules/bcrypt 
node-pre-gyp ERR! node -v v7.8.0 
node-pre-gyp ERR! node-pre-gyp -v v0.6.36 
node-pre-gyp ERR! not ok 
Failed to execute '/opt/node-v7.8.0-linux-x64/bin/node /opt/node-v7.8.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/opt/PROJECT_NAME/MS-NAME/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/opt/PROJECT_NAME/MS-NAME/node_modules/bcrypt/lib/binding' (1) 
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command. 

```

**Comment by agathver** [comment]
https://github.com/nodejs/node-gyp/issues/235

Note `--nodedir` must point to a directory containing nodejs sources (or headers)

**Comment by abdennour** [comment]
any update ? node-saas give a way thru env var `SASS_BINARY_SITE`. what about bcrypt ?
