### ISSUE TITLE
Windows 10 : node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v59-win32-x64.tar.gz

### ISSUE THREAD

**Issue by nimatullah** [kelektiv/node.bcrypt.js#571]
I have install all prerequisties, but still I can not install it. 

```
D:\workstation\jobsaf-server>npm install

> bcrypt@1.0.3 install D:\workstation\jobsaf-server\node_modules\bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v59-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.3 and node@9.3.0 (node-v59 ABI) (falling back to source compile with node-gyp)
gyp ERR! build error
gyp ERR! stack Error: Command failed: reg query "HKLM\Software\Microsoft\MSBuild\ToolsVersions" /s /reg:32
gyp ERR! stack ERROR: Registry editing has been disabled by your administrator.
gyp ERR! stack
gyp ERR! stack Can't find "msbuild.exe". Do you have Microsoft Visual Studio C++ 2008+ installed?
gyp ERR! stack     at D:\workstation\jobsaf-server\node_modules\node-gyp\lib\build.js:138:25
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:279:5)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:943:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\workstation\\jobsaf-server\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=D:\\workstation\\jobsaf-server\\node_modules\\bcrypt\\lib\\binding\\bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=D:\\workstation\\jobsaf-server\\node_modules\\bcrypt\\lib\\binding"
gyp ERR! cwd D:\workstation\jobsaf-server\node_modules\bcrypt
gyp ERR! node -v v9.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe D:\workstation\jobsaf-server\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=D:\workstation\jobsaf-server\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=D:\workstation\jobsaf-server\node_modules\bcrypt\lib\binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\workstation\jobsaf-server\node_modules\bcrypt\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:943:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
node-pre-gyp ERR! System Windows_NT 10.0.16299
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\workstation\\jobsaf-server\\node_modules\\bcrypt\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\workstation\jobsaf-server\node_modules\bcrypt
node-pre-gyp ERR! node -v v9.3.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe D:\workstation\jobsaf-server\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=D:\workstation\jobsaf-server\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=D:\workstation\jobsaf-server\node_modules\bcrypt\lib\binding' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@1.0.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@1.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nimatullah.razmjo\AppData\Roaming\npm-cache\_logs\2018-01-16T08_47_42_237Z-debug.log
```

The above log explain everything.

**Comment by agathver** [comment]
Pre built binaries for node 9 are not available.

**Comment by agathver** [comment]
Prebuild binaries for windows are now available

**Comment by Harishan15** [comment]
I had this issue. Use this following link as a reference to solve this issue.

https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions
