### ISSUE TITLE
Node Version Problem

### ISSUE THREAD

**Issue by vinothmoorthkumar** [kelektiv/node.bcrypt.js#576]
Hi,
     I have upgraded my node version from 6 to 8. Now i m facing error from bcrypt.

return process.dlopen(module, path._makeLong(filename));
                 ^
Error: The module '/home/Documents/projects//node_modules/bcrypt/lib/binding/bcrypt_lib.node'

**Comment by vidukapoor** [comment]
hi @vinothmoorthkumar are you using docker for deployment?

**Comment by agathver** [comment]
Yes. When you upgrade node versions you need to rebuild all native modules. 
npm rebuild bcrypt

**Comment by RolandBarro** [comment]
I am having this error when I execute `docker build -t docker-test-image .`
----
My Dockerfile:
`FROM node:8.11`
`WORKDIR /app`
`COPY package.json /app`
`COPY package-lock.json /app`
`RUN npm install`
`COPY . /app`
`CMD npm start`

*Error:*
module.js:681
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: /app/node_modules/scrypt/build/Release/scrypt.node: invalid ELF header
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/node_modules/scrypt/index.js:3:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
