### ISSUE TITLE
Failed at the bcrypt@0.8.7 install script error

### ISSUE THREAD

**Issue by jgfidelis** [kelektiv/node.bcrypt.js#579]
When I run `npm install` I get this error, I don't know if this is the correct place to open an issue...

```
jgfidelis$ npm install

> bcrypt@0.8.7 install my_project/node_modules/bcrypt
> node-gyp rebuild

  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
clang: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX' [-Wincompatible-sysroot]
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
clang: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX' [-Wincompatible-sysroot]
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
clang: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX' [-Wincompatible-sysroot]
In file included from ../src/bcrypt_node.cc:1:
In file included from ../../nan/nan.h:190:
../../nan/nan_maybe_43_inl.h:88:15: warning: 'ForceSet' is deprecated
      [-Wdeprecated-declarations]
  return obj->ForceSet(GetCurrentContext(), key, value, attribs);
              ^
/Users/jgfidelis/.node-gyp/9.4.0/include/node/v8.h:3114:3: note: 'ForceSet' has
      been explicitly marked deprecated here
  V8_DEPRECATED("Use CreateDataProperty / DefineOwnProperty",
  ^
/Users/jgfidelis/.node-gyp/9.4.0/include/node/v8config.h:321:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
1 warning generated.
  SOLINK_MODULE(target) Release/bcrypt_lib.node
clang: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX' [-Wincompatible-sysroot]
ld: building for OSX, but linking against dylib built for iOS (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk/usr/lib/libc++.tbd). file '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk/usr/lib/libc++.tbd' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/bcrypt_lib.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/jgfidelis/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/Users/jgfidelis/.nvm/versions/node/v9.4.0/bin/node" "/Users/jgfidelis/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /my_project/node_modules/bcrypt
gyp ERR! node -v v9.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN koa-graphql@0.6.3 requires a peer of graphql@^0.9.2 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.8.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jgfidelis/.npm/_logs/2018-02-17T14_51_45_266Z-debug.log
```

Node: 9.4.0
node-gyp 3.6.2
npm version: 3.10.10

xcode stuff:
```
jgfidelis$ xcode-select --print-path
/Applications/Xcode.app/Contents/Developer
```
```
jgfidelis$ xcodebuild -version
Xcode 9.2
Build version 9C40b
```

This is (probably) not a problem with bcrypt, but with my env! I hope you guys can help me anyway!

Any tips? Any additional information you may need, just ask! I cannot find anyone with a similar error on the internet haha

**Comment by agathver** [comment]
```
clang: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX' [-Wincompatible-sysroot]
```

I'm do not possess much knowledge of XCode, but I think, that line summarizes whats wrong.

**Comment by agathver** [comment]
Please update to v1.0.3 to automatically install Node9 binaries from remote without the need to compile.

**Comment by jgfidelis** [comment]
@agathver Yup, I agree with you that the `clang` line summarizes whats wrong, but I do not know how to fix this, unfortunately. I have tried a lot of stuff...

**Comment by agathver** [comment]
@jgfidelis Apple's man pages suggest doing a `xcode-select --install`. I won't be able to help beyond this point, I don't own a mac, unfortunately.

**Comment by jgfidelis** [comment]
@agathver No problem, thanks for the help.

I am trying to follow your v1.0.3 suggestion!

bcrypt is not a dependency in our project, but a dependency for a library that we use, I believe. I am new to JS development so I may be doing something wrong.

I added to our `package.json` inside the dependencies field: `"bcrypt": "1.0.3",`

But I am still getting the bcrypt@0.87 build error. Am I doing something wrong? I think your suggestion might solve this but I am missing a step.

**Comment by jgfidelis** [comment]
I added:
```
"resolutions": {
    "bcrypt-as-promised/bcrypt": "1.0.3"
  },
```

And it fixed my error. Thanks!

**Comment by agathver** [comment]
@jgfidelis, We added  promises in v1.0.0, so you will not need bcrypt-as-promised anymore  :)

**Comment by jgfidelis** [comment]
I noticed this, we will change to bcrypt only on our project! thanks!

**Comment by LukeV111** [comment]
What solved the issue for me was changing my XCode command Line Tools for 10.1 to 9.4 (I have both versions installed).

If you have both versions installed you can do this by going to Xcode > Preferences > Locations and switching you Command Line Tools there. It seems XCOde 10+ is currently incompatible.
