### ISSUE TITLE
bcrypt error when deploy on Heroku : invalid ELF header

### ISSUE THREAD

**Issue by bnkhoi** [kelektiv/node.bcrypt.js#595]
I am using node v9.1.0
I run the project locally at localhost and it works fine but when I deploy it on Heroku then I got these logs from Heroku:

2018-04-18T23:09:40.062371+00:00 app[web.1]: module.js:681
2018-04-18T23:09:40.062409+00:00 app[web.1]:   return process.dlopen(module, path._makeLong(filename));
2018-04-18T23:09:40.062411+00:00 app[web.1]:                  ^
2018-04-18T23:09:40.062413+00:00 app[web.1]: 
2018-04-18T23:09:40.062420+00:00 app[web.1]: Error: /app/node_modules/bcrypt/lib/binding/bcrypt_lib.node: invalid ELF header
2018-04-18T23:09:40.062422+00:00 app[web.1]:     at Object.Module._extensions..node (module.js:681:18)
2018-04-18T23:09:40.062424+00:00 app[web.1]:     at Module.load (module.js:565:32)
2018-04-18T23:09:40.062425+00:00 app[web.1]:     at tryModuleLoad (module.js:505:12)
2018-04-18T23:09:40.062427+00:00 app[web.1]:     at Function.Module._load (module.js:497:3)
2018-04-18T23:09:40.062428+00:00 app[web.1]:     at Module.require (module.js:596:17)
2018-04-18T23:09:40.062430+00:00 app[web.1]:     at require (internal/module.js:11:18)
2018-04-18T23:09:40.062431+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/bcrypt/bcrypt.js:6:16)
2018-04-18T23:09:40.062433+00:00 app[web.1]:     at Module._compile (module.js:652:30)
2018-04-18T23:09:40.062435+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:663:10)
2018-04-18T23:09:40.062436+00:00 app[web.1]:     at Module.load (module.js:565:32)
2018-04-18T23:09:40.062438+00:00 app[web.1]:     at tryModuleLoad (module.js:505:12)
2018-04-18T23:09:40.062439+00:00 app[web.1]:     at Function.Module._load (module.js:497:3)
2018-04-18T23:09:40.062441+00:00 app[web.1]:     at Module.require (module.js:596:17)
2018-04-18T23:09:40.062442+00:00 app[web.1]:     at require (internal/module.js:11:18)
2018-04-18T23:09:40.062444+00:00 app[web.1]:     at Object.<anonymous> (/app/api/routes/user.js:4:16)
2018-04-18T23:09:40.062445+00:00 app[web.1]:     at Module._compile (module.js:652:30)

Please help . Thanks for your reading.

**Comment by swapnildubal** [comment]
Even I am facing the same issue

**Comment by agathver** [comment]
You are probably pushing your node_modules folder to heroku.

**Comment by bnkhoi** [comment]
No, i am not. I add the node_modules in the .gitignore file :(

**Comment by TheBrotherFromASouthernMother** [comment]
I seem to be running into the exact same issue. I ran reinstalled bcrypt on my heroku dyno and still get the same error

**Comment by agathver** [comment]
@bnkhoi I was unable to replicate your issue. I have a heroku app running here using bcrypt@2.0.1 http://bcrypt-demo.herokuapp.com/

**Comment by agathver** [comment]
@bnkhoi I was unable to replicate your issue. I have a heroku app running here using bcrypt@2.0.1 http://bcrypt-demo.herokuapp.com/

Code: https://github.com/agathver/bcrypt-demo

**Comment by bnkhoi** [comment]
@agathver It seems there are some problems with my .gitignore file, it wasn't actually work.
Just for some guys above, I fixed it by these command in terminal: 

> git rm -r --cached .
> git add .
> git commit -m "fixed untracked files"

@agathver I don't know why when I run "npm install bcrypt --save" then it installed the 1.0.3 version. I have to run "npm install bcrypt@2.0.1 --save" to update to your version. 
Thanks for your time. @agathver

**Comment by TheBrotherFromASouthernMother** [comment]
Finally solved my problem as well.  It seems that on top of the issue with pushing node modules to Heroku, my problem was caused by requiring bcrypt independently in multiple modules. I deleted these individual imports, and refactored them into one single import in my main app.js file and exported into the other modules from there. 

Example:

In app.js:
`const bcrypt = require('bcrypt');
const saltRounds = 10;
module.exports.bcrypt = bcrypt;`

In my user registration route:
`const bcrypt = require('../app.js').bcrypt`

**Comment by agathver** [comment]
@TheBrotherFromASouthernMother I'm glad it worked out for you.

>It seems that on top of the issue with pushing node modules to Heroku, my problem was caused by requiring bcrypt independently in multiple modules.

It is really very strange, this is not how NodeJS should work. It should make no difference when you include a module in multiple files or even across modules. _Each module is require'd only once per application and cached in memory, the next require call just returns the copy_

**Comment by XinnieSol** [comment]
Another option is to:
1. uninstall bcrypt
2. then install bcryptjs. 
3. Replace every instance of bcrypt in your code with bcryptjs

**Comment by pshantanu771** [comment]
> @agathver It seems there are some problems with my .gitignore file, it wasn't actually work. Just for some guys above, I fixed it by these command in terminal:
> 
> > git rm -r --cached .
> > git add .
> > git commit -m "fixed untracked files"
> 
> @agathver I don't know why when I run "npm install bcrypt --save" then it installed the 1.0.3 version. I have to run "npm install bcrypt@2.0.1 --save" to update to your version. Thanks for your time. @agathver

Thanks man!! My issue got solved

**Comment by SOMUS-TECH** [comment]
@XinnieSol Thank you so much this solution work for me
uninstall bcrypt
then install bcryptjs.
Replace every instance of bcrypt in your code with bcryptjs

**Comment by adshay18** [comment]
> Another option is to:
> 
> 1. uninstall bcrypt
> 2. then install bcryptjs.
> 3. Replace every instance of bcrypt in your code with bcryptjs

This worked for me!

**Comment by thatxx142** [comment]
Another option is to:

uninstall bcrypt
then install bcryptjs.
Replace every instance of bcrypt in your code with bcryptjs
This worked for me!
