### ISSUE TITLE
npm ERR! 404 Not Found: bcrycpt@latest - Windows 10 Pro

### ISSUE THREAD

**Issue by oshihirii** [kelektiv/node.bcrypt.js#605]
Using Node `10.0.0` and `8.11.1` on `Windows 10 Pro` I get:  

```
npm install --save jsonwebtoken bcrycpt
npm ERR! code E404
npm ERR! 404 Not Found: bcrycpt@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Me\AppData\Roaming\npm-cache\_logs\2018-05-08T08_13_28_000Z-debug.log
```

Seems to be the same issue discussed here:  https://github.com/kelektiv/node.bcrypt.js/issues/476

Log file contents below:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'jsonwebtoken',
1 verbose cli   'bcrycpt' ]
2 info using npm@5.6.0
3 info using node@v8.11.1
4 verbose npm-session ff773029f5339dce
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/jsonwebtoken 245ms (from cache)
8 silly pacote tag manifest for jsonwebtoken@latest fetched in 280ms
9 http fetch GET 404 https://registry.npmjs.org/bcrycpt 3708ms
10 silly fetchPackageMetaData error for bcrycpt@latest 404 Not Found: bcrycpt@latest
11 verbose stack Error: 404 Not Found: bcrycpt@latest
11 verbose stack     at fetch.then.res (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
11 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
11 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
11 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
11 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
11 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
11 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
11 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
11 verbose stack     at Immediate.Async.drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
11 verbose stack     at runCallback (timers.js:794:20)
11 verbose stack     at tryOnImmediate (timers.js:752:5)
11 verbose stack     at processImmediate [as _immediateCallback] (timers.js:729:5)
12 verbose cwd C:\Users\Me\Documents\my_repo\my_dir
13 verbose Windows_NT 10.0.16299
14 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "jsonwebtoken" "bcrycpt"
15 verbose node v8.11.1
16 verbose npm  v5.6.0
17 error code E404
18 error 404 Not Found: bcrycpt@latest
19 verbose exit [ 1, true ]
```

**Comment by agathver** [comment]
The package is
`bcrypt` not `bcrycpt`.

**Comment by oshihirii** [comment]
I am so sorry!  Ergh I spent a couple of hours looking for a solution to this :/.
