### ISSUE TITLE
How to install v3?

### ISSUE THREAD

**Issue by gustawdaniel** [kelektiv/node.bcrypt.js#624]
Command

    npm i -S bcrypt@3

Gives

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for bcrypt@3
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/daniel/.npm/_logs/2018-07-04T11_26_16_094Z-debug.log
```

And logs contains:

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/daniel/.nvm/versions/node/v8.11.1/bin/node',
1 verbose cli   '/home/daniel/.nvm/versions/node/v8.11.1/bin/npm',
1 verbose cli   'i',
1 verbose cli   '-S',
1 verbose cli   'bcrypt@3' ]
2 info using npm@6.1.0
3 info using node@v8.11.1
4 verbose npm-session b38ba17ffa16c6e5
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/bcrypt 64ms (from cache)
8 silly registry:manifest no matching version for bcrypt@3 in the cache. Forcing revalidation
9 http fetch GET 304 https://registry.npmjs.org/bcrypt 176ms (from cache)
10 silly fetchPackageMetaData error for bcrypt@3 No matching version found for bcrypt@3
11 timing stage:rollbackFailedOptional Completed in 1ms
12 timing stage:runTopLevelLifecycles Completed in 1014ms
13 verbose type range
14 verbose stack bcrypt: No matching version found for bcrypt@3
14 verbose stack     at pickManifest (/home/daniel/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:65:11)
14 verbose stack     at fetchPackument.then.packument (/home/daniel/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:52:18)
14 verbose stack     at tryCatcher (/home/daniel/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
14 verbose stack     at Promise._settlePromiseFromHandler (/home/daniel/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
14 verbose stack     at Promise._settlePromise (/home/daniel/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
14 verbose stack     at Promise._settlePromise0 (/home/daniel/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
14 verbose stack     at Promise._settlePromises (/home/daniel/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
14 verbose stack     at Async._drainQueue (/home/daniel/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
14 verbose stack     at Async._drainQueues (/home/daniel/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
14 verbose stack     at Immediate.Async.drainQueues (/home/daniel/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
14 verbose stack     at runCallback (timers.js:794:20)
14 verbose stack     at tryOnImmediate (timers.js:752:5)
14 verbose stack     at processImmediate [as _immediateCallback] (timers.js:729:5)
15 verbose cwd /home/daniel/pro/omnisys/v3
16 verbose Linux 4.15.0-24-generic
17 verbose argv "/home/daniel/.nvm/versions/node/v8.11.1/bin/node" "/home/daniel/.nvm/versions/node/v8.11.1/bin/npm" "i" "-S" "bcrypt@3"
18 verbose node v8.11.1
19 verbose npm  v6.1.0
20 error code ETARGET
21 error notarget No matching version found for bcrypt@3
22 error notarget In most cases you or one of your dependencies are requesting
22 error notarget a package version that doesn't exist.
23 verbose exit [ 1, true ]
```

**Comment by gustawdaniel** [comment]
I installed by:

    npm i -S git+https://github.com/kelektiv/node.bcrypt.js

But with WARNS:

```
> bcrypt@3.0.0 install /home/daniel/pro/omnisys/v3/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.0/bcrypt_lib-v3.0.0-node-v57-linux-x64-glibc.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for bcrypt@3.0.0 and node@8.11.1 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
make: Entering directory '/home/daniel/pro/omnisys/v3/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
../src/bcrypt.cc: In function ‘void encode_salt(char*, u_int8_t*, char, u_int16_t, u_int8_t)’:
../src/bcrypt.cc:114:1: warning: ‘__builtin___snprintf_chk’ output may be truncated before the last format character [-Wformat-truncation=]
 encode_salt(char *salt, u_int8_t *csalt, char minor, u_int16_t clen, u_int8_t logr)
 ^~~~~~~~~~~
In file included from /usr/include/stdio.h:862:0,
                 from ../src/bcrypt.cc:34:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:65:44: note: ‘__builtin___snprintf_chk’ output between 4 and 5 bytes into a destination of size 4
        __bos (__s), __fmt, __va_arg_pack ());
                                            ^
../src/bcrypt.cc: In function ‘void bcrypt(const char*, const char*, char*)’:
../src/bcrypt.cc:147:1: warning: ‘__builtin___snprintf_chk’ output may be truncated before the last format character [-Wformat-truncation=]
 bcrypt(const char *key, const char *salt, char *encrypted)
 ^~~~~~
In file included from /usr/include/stdio.h:862:0,
                 from ../src/bcrypt.cc:34:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:65:44: note: ‘__builtin___snprintf_chk’ output between 4 and 5 bytes into a destination of size 4
        __bos (__s), __fmt, __va_arg_pack ());
                                            ^
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
  SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
  COPY Release/bcrypt_lib.node
  COPY /home/daniel/pro/omnisys/v3/node_modules/bcrypt/lib/binding/bcrypt_lib.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Leaving directory '/home/daniel/pro/omnisys/v3/node_modules/bcrypt/build'
+ bcrypt@3.0.0
added 64 packages from 45 contributors and audited 953 packages in 44.781s
found 0 vulnerabilities
```

Is there minimal node version that is recommended for v3? Like node 4 for bcrypt v2?

**Comment by agathver** [comment]
V3 is not yet released as it's not a really important update.

**Comment by freewil** [comment]
> V3 is not yet released as it's not a really important update.

This is really confusing as node v10 support is listed as >=3.0.0, but makes no mention of this fact.

**Comment by freewil** [comment]
I opened #627 to add a note to the readme.
