### ISSUE TITLE
v3.0.1/bcrypt_lib-v3.0.1-node-v57-win32-x64-unknown.tar.gz   ?

### ISSUE THREAD

**Issue by summertong** [kelektiv/node.bcrypt.js#655]
```
PS D:\workHome\lianheng-app> cnpm i
√ Installed 70 packages
√ Linked 1 latest versions
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp http GET https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.1/bcrypt_lib-v3.0.1-node-v57-win32-x64-unknown.tar.gz
node-pre-gyp http 404 https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.1/bcrypt_lib-v3.0.1-node-v57-win32-x64-unknown.tar.gz
node-pre-gyp WARN Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.1/bcrypt_lib-v3.0.1-node-v57-win32-x64-unknown.tar.gz
node-pre-gyp WARN Pre-built binaries not found for bcrypt@3.0.1 and node@8.11.3 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.1/bcrypt_lib-v3.0.1-node-v57-win32-x64-unknown.tar.gz
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (D:\workHome\lianheng-app\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (D:\workHome\lianheng-app\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at D:\workHome\lianheng-app\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\workHome\\lianheng-app\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=D:\\workHome\\lianheng-app\\node_modules\\_bcrypt@3.0.1@bcrypt\\lib\\binding\\bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=D:\\workHome\\lianheng-app\\node_modules\\_bcrypt@3.0.1@bcrypt\\lib\\binding" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v57"
gyp ERR! cwd D:\workHome\lianheng-app\node_modules\_bcrypt@3.0.1@bcrypt
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

**Comment by agathver** [comment]
Windows builds are not yet available

**Comment by LebonNic** [comment]
Hi! How long will it take (approximately) to upload the builds for Windows ? Thanks in advance.

**Comment by carboneater** [comment]
The README states the builds are provided on a voluntary basis...
But there is no instructions on what to do to contribute those builds...

Is there a way for people to volunteer their builds?
Or is a build chain taking care of that now?

**Comment by agathver** [comment]
@carboneater There was a CI issue that prevented the builds from being published. If you are a PowerShell user, please contribute to the appveyor config to automate the builds. Specifically, there is a regex that needs fixing.

Builds are not made available automatically for Linux and macOS
