### ISSUE TITLE
BCrypt fails to install on Node v12.4.0

### ISSUE THREAD

**Issue by Z3roCoder** [kelektiv/node.bcrypt.js#730]
Hello there. I have seen that there are Problems with non-Stable releases of Node and the BCrypt-Packages.

Is there any way to get Node 12.4.0 to work with BCrypt at the moment?

My Install fails with the following Message:

```
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Python373\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:290:12)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\SomeUser\\Desktop\\NodeJS_Test\\node_modules\\bcrypt\\lib\\binding\\bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=C:\\Users\\SomeUser\\Desktop\\NodeJS_Test\\node_modules\\bcrypt\\lib\\binding" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd C:\Users\SomeUser\Desktop\NodeJS_Test\node_modules\bcrypt
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\SomeUser\Desktop\NodeJS_Test\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=C:\Users\SomeUser\Desktop\NodeJS_Test\node_modules\bcrypt\lib\binding --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\SomeUser\Desktop\NodeJS_Test\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\SomeUser\\Desktop\\NodeJS_Test\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\SomeUser\Desktop\NodeJS_Test\node_modules\bcrypt
node-pre-gyp ERR! node -v v12.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\SomeUser\Desktop\NodeJS_Test\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=C:\Users\SomeUser\Desktop\NodeJS_Test\node_modules\bcrypt\lib\binding --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
npm WARN nodejs_test@0.0.1 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@3.0.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@3.0.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SomeUser\AppData\Roaming\npm-cache\_logs\2019-06-09T18_50_30_334Z-debug.log
```

**Comment by agathver** [comment]
You use python 3. Unfortunately, the installer requires python 2.

Prebuilt binaries will be available by next weekend.

**Comment by Z3roCoder** [comment]
Oh, awesome. Is there anything I have to do to use the prebuilt ones, or
does npm manage this on its own?

Amitosh Swain Mahapatra <notifications@github.com> schrieb am So., 9. Juni
2019, 23:26:

**Comment by agathver** [comment]
NPM will handle it

**Comment by mattcollier** [comment]
Hello, what is the status of Node 12 support?  I see commits on master related to Node 12, but CI on the last commit is failing across the board.  If Node 12 support is in place, will we be seeing a release soon?  

Thank you!

**Comment by mattcollier** [comment]
Just did an install using master bbf0099fecaffc7c9553dba5d4b4311e2f98fe47 and it builds successfully with Node 12.10.0, but there are not yet pre-built binaries:
```
> bcrypt@3.0.6 install /home/matt/dev/bedrock-dev/iprpoc-cbp/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.6/bcrypt_lib-v3.0.6-node-v72-linux-x64-glibc.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for bcrypt@3.0.6 and node@12.10.0 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
```
