### ISSUE TITLE
Not expected error: bcrypt.compare doen't work

### ISSUE THREAD

**Issue by Aleksey-Danchin** [kelektiv/node.bcrypt.js#732]
I used the bcrypt in other projects, and for still haven't a problem. But today I can to force the bcrypt works. I follow all the recommendations in the documentation.

Logs:

```
 TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be one of type Buffer, TypedArray, DataView, string, or KeyObject. Received type number
      at prepareSecretKey (internal/crypto/keys.js:299:13)
      at new Hmac (internal/crypto/hash.js:98:9)
      at Object.createHmac (crypto.js:139:10)
      at sign (/home/old/Desktop/JsPlaceStudy/backend/node_modules/keygrip/index.js:22:8)
      at Keygrip.sign (/home/old/Desktop/JsPlaceStudy/backend/node_modules/keygrip/index.js:29:38)
      at Cookies.set (/home/old/Desktop/JsPlaceStudy/backend/node_modules/cookies/index.js:109:30)
      at ContextSession.save (/home/old/Desktop/JsPlaceStudy/backend/node_modules/koa-session/lib/context.js:332:22)
      at ContextSession.commit (/home/old/Desktop/JsPlaceStudy/backend/node_modules/koa-session/lib/context.js:238:16)
      at session (/home/old/Desktop/JsPlaceStudy/backend/node_modules/koa-session/index.js:46:20)
      at bodyParser (/home/old/Desktop/JsPlaceStudy/backend/node_modules/koa-bodyparser/index.js:86:5)
```

Environment: Node v12.4.0, npm v6.9.0, bcrypt v3.0.6.

During the installation an error appeared like this:
https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions
- but it did not help

**Comment by agathver** [comment]
Please share a code snippet that fails 

From the stacktrace doesn't look like bcrypt is throwing it

**Comment by Aleksey-Danchin** [comment]
I'm sorry. I have solved so many problems in the last 8 hours. Including one of the problems was with bcrypt. The bcrypt works fine. Another module is not working.
