### ISSUE TITLE
cannot install bcrypt

### ISSUE THREAD

**Issue by deeprobin** [kelektiv/node.bcrypt.js#735]
Installation fails
```
robin@ROBIN-PC MINGW64 /f/Minecraft/rcon-webinterface (master)
$ npm install bcrypt @types/bcrypt --save

> bcrypt@3.0.6 install F:\Minecraft\rcon-webinterface\node_modules\bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.6/bcrypt_lib-v3.0.6-node-v72-win32-x64-unknown.tar.gz     
node-pre-gyp WARN Pre-built binaries not found for bcrypt@3.0.6 and node@12.3.1 (node-v72 ABI, unknown) (falling back to source compile with node-gyp) 
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack Error: spawn E:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:456:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:84:9)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "E:\\Program Files\\nodejs\\node.exe" "E:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=F:\\Minecraft\\rcon-webinterface\\node_modules\\bcrypt\\lib\\binding\\bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=F:\\Minecraft\\rcon-webinterface\\node_modules\\bcrypt\\lib\\binding" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd F:\Minecraft\rcon-webinterface\node_modules\bcrypt
gyp ERR! node -v v12.3.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'E:\Program Files\nodejs\node.exe 
E:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=F:\Minecraft\rcon-webinterface\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=F:\Minecraft\rcon-webinterface\node_modules\bcrypt\lib\binding --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (7)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (F:\Minecraft\rcon-webinterface\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)      
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Windows_NT 10.0.18362
node-pre-gyp ERR! command "E:\\Program Files\\nodejs\\node.exe" "F:\\Minecraft\\rcon-webinterface\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd F:\Minecraft\rcon-webinterface\node_modules\bcrypt
node-pre-gyp ERR! node -v v12.3.1
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok 
Failed to execute 'E:\Program Files\nodejs\node.exe E:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=F:\Minecraft\rcon-webinterface\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=F:\Minecraft\rcon-webinterface\node_modules\bcrypt\lib\binding --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (7)
npm WARN acorn-jsx@5.0.1 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN rcon-webinterface@1.0.0 No repository field.
npm WARN rcon-webinterface@1.0.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@3.0.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@3.0.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\robin\AppData\Roaming\npm-cache\_logs\2019-07-01T14_09_50_241Z-debug.log
```

npm version: 6.9.0
node version: v12.3.1

**Comment by YasharF** [comment]
Have you tried https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions#microsoft-windows ?

Is this still an issue? Can this be closed?

**Comment by SHIVAMSINGH0101** [comment]
> Have you tried https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions#microsoft-windows ?
> 
> Is this still an issue? Can this be closed?

This link helped. Thanks a lot
