### ISSUE TITLE
Bcrypt fails install on node11-alpine docker image even with rebuild from source

### ISSUE THREAD

**Issue by CMatias** [kelektiv/node.bcrypt.js#741]
Docker build output log: 

```
Step 8/12 : RUN npm rebuild bcrypt --build-from-source
 ---> Running in d72bc81aad44

> bcrypt@3.0.6 install /opt/app/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
make: Entering directory '/opt/app/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
In file included from ../src/bcrypt_node.cc:1:
../node_modules/nan/nan.h: In function 'void Nan::AsyncQueueWorker(Nan::AsyncWorker*)':
../node_modules/nan/nan.h:2232:62: warning: cast between incompatible function types from 'void (*)(uv_work_t*)' {aka 'void (*)(uv_work_s*)'} to 'uv_after_work_cb' {aka 'void (*)(uv_work_s*, int)'} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
In file included from ../node_modules/nan/nan.h:53,
                 from ../src/bcrypt_node.cc:1:
../src/bcrypt_node.cc: At global scope:
/root/.node-gyp/11.15.0/include/node/node.h:544:43: warning: cast between incompatible function types from 'void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)' {aka 'void (*)(v8::Local<v8::Object>)'} to 'node::addon_register_func' {aka 'void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)'} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/root/.node-gyp/11.15.0/include/node/node.h:578:3: note: in expansion of macro 'NODE_MODULE_X'
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../src/bcrypt_node.cc:378:1: note: in expansion of macro 'NODE_MODULE'
 NODE_MODULE(bcrypt_lib, init);
 ^~~~~~~~~~~
In file included from /root/.node-gyp/11.15.0/include/node/node.h:63,
                 from ../node_modules/nan/nan.h:53,
                 from ../src/bcrypt_node.cc:1:
/root/.node-gyp/11.15.0/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]':
/root/.node-gyp/11.15.0/include/node/node_object_wrap.h:84:78:   required from here
/root/.node-gyp/11.15.0/include/node/v8.h:9710:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<node::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
                reinterpret_cast<Callback>(callback), type);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/.node-gyp/11.15.0/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]':
../node_modules/nan/nan_object_wrap.h:65:61:   required from here
/root/.node-gyp/11.15.0/include/node/v8.h:9710:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
  SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
  COPY Release/bcrypt_lib.node
  COPY /opt/app/node_modules/bcrypt/lib/binding/bcrypt_lib.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Leaving directory '/opt/app/node_modules/bcrypt/build'
bcrypt@3.0.6 /opt/app/node_modules/bcrypt
```

Once the app starts I get the following:
```
app_1  | internal/modules/cjs/loader.js:857
app_1  |   return process.dlopen(module, path.toNamespacedPath(filename));
app_1  |                  ^
app_1  |
app_1  | Error: Error loading shared library /opt/app/node_modules/bcrypt/lib/binding/bcrypt_lib.node: Exec format error
app_1  |     at Object.Module._extensions..node (internal/modules/cjs/loader.js:857:18)
app_1  |     at Module.load (internal/modules/cjs/loader.js:685:32)
app_1  |     at Function.Module._load (internal/modules/cjs/loader.js:620:12)
app_1  |     at Module.require (internal/modules/cjs/loader.js:723:19)
app_1  |     at require (internal/modules/cjs/helpers.js:14:16)
app_1  |     at Object.<anonymous> (/opt/app/node_modules/bcrypt/bcrypt.js:6:16)
app_1  |     at Module._compile (internal/modules/cjs/loader.js:816:30)
app_1  |     at Module._compile (/opt/app/node_modules/pirates/lib/index.js:99:24)
app_1  |     at Module._extensions..js (internal/modules/cjs/loader.js:827:10)
app_1  |     at Object.newLoader [as .js] (/opt/app/node_modules/pirates/lib/index.js:104:7)
app_1  | npm ERR! code ELIFECYCLE
```

My Docker file: 
```
FROM node:11-alpine

RUN mkdir -p /opt/app

ENV NODE_ENV production

WORKDIR /opt/app
COPY . /opt/app/

RUN apk add --no-cache make gcc g++ python && \
  npm install && \
  apk del make gcc g++ python

RUN npm rebuild bcrypt --build-from-source

RUN npm run build

EXPOSE 8000

CMD [ "npm", "start" ]
```

**Comment by agathver** [comment]
The logs show that the module is built correctly but I think you are
pulling in node_modules from the host. Check if node_modules is in your
dockerignore

**Comment by CMatias** [comment]
Thanks a lot @agathver, I was actually ignoring the host's node_modules but I was uncorrectly mouting my volumes which were passing the node_modules again.

**Comment by nawaazwill11** [comment]
Thanks @recrsn! This solution solved my problem.

**Comment by PQMISSCMP** [comment]
Thank @CMatias

**Comment by PQMISSCMP** [comment]
thankkk @recrsn

**Comment by Yeab13** [comment]
I was having issues for the past 2 days. Thank You so much @recrsn.

**Comment by sokunsamnang** [comment]
I facing the same problem. so, we have to ignore node_modules in dockerignore too?

**Comment by CesarOliveira** [comment]
> I facing the same problem. so, we have to ignore node_modules in dockerignore too?

I change `bcrypt` to use `bcryptjs` instead, and worked perfectly
