### ISSUE TITLE
pakage not found 

### ISSUE THREAD

**Issue by matamune94** [kelektiv/node.bcrypt.js#757]
this link https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.6/bcrypt_lib-v3.0.6-node-v72-linux-x64-glibc.tar.gz

not found, how setup ?

**Comment by Slavvkko** [comment]
I have the same problem.

**Comment by Slavvkko** [comment]
For resolve this error you need to install `node-gyp` first to global
`yarn global add node-gyp`

**Comment by bouteillerAlan** [comment]
:heavy_check_mark: I have the same problem.

### Some version
```
node -v
v12.13.0
yarn -v
1.19.1

OS: Manjaro 18.1.3 Juhraya
Kernel: x86_64 Linux 5.3.11-1-MANJARO
Shell: zsh 5.7.1
```

### My log
```
yarn add bcrypt

yarn add v1.19.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[-/4] ⡀ waiting...
[2/4] ⡀ @nestjs/core
[-/4] ⡀ waiting...
error /mnt/samus/project/helloplanet/back/node_modules/bcrypt: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /mnt/samus/project/helloplanet/back/node_modules/bcrypt
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.12.0
node-pre-gyp info using node@12.13.0 | linux | x64
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp info check checked for "/mnt/samus/project/helloplanet/back/node_modules/bcrypt/lib/binding/bcrypt_lib.node" (not found)
node-pre-gyp http GET https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.6/bcrypt_lib-v3.0.6-node-v72-linux-x64-glibc.tar.gz
node-pre-gyp http 404 https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.6/bcrypt_lib-v3.0.6-node-v72-linux-x64-glibc.tar.gz
node-pre-gyp WARN Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.6/bcrypt_lib-v3.0.6-node-v72-linux-x64-glibc.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for bcrypt@3.0.6 and node@12.13.0 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.6/bcrypt_lib-v3.0.6-node-v72-linux-x64-glibc.tar.gz 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp clean' (Error: spawn node-gyp ENOENT)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/mnt/samus/project/helloplanet/back/node_modules/node-pre-gyp/lib/util/compile.js:77:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
node-pre-gyp ERR! stack     at onErrorNT (internal/child_process.js:456:16)
node-pre-gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
node-pre-gyp ERR! System Linux 5.3.11-1-MANJARO
node-pre-gyp ERR! command "/usr/bin/node" "/mnt/samus/project/helloplanet/back/node_modules/bcrypt/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /mnt/samus/project/helloplanet/back/node_modules/bcrypt
node-pre-gyp ERR! node -v v12.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
```

### The error (i think)
```
node-pre-gyp http GET https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.6/bcrypt_lib-v3.0.6-node-v72-linux-x64-glibc.tar.gz
node-pre-gyp http 404 https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.6/bcrypt_lib-v3.0.6-node-v72-linux-x64-glibc.tar.gz
```
After a rapid check the 404 is here because the package doesn't exist in the git repo (the last for linux is the node-v67).

### My question

Why this error ? 

Yesterday i use the same command and everything worked fine, after a re-install of my workstation the error appear. However i have installed node and yarn in the same way (and bcrypt too).

### The *solution* 

> For resolve this error you need to install `node-gyp` first to global
> `yarn global add node-gyp`

This solution works, but [...] why ? I have never installed this package before :thinking:

**Comment by Slavvkko** [comment]
`bcrypt` will compile native binary code for your OS, `node-gyp` will do this stuff. Usually you have this package as a dependency with `npm`. I guess you like a me removed this package and use only the `yarn`.
