### ISSUE TITLE
not work with node v12.13.0

### ISSUE THREAD

**Issue by Hesamp** [kelektiv/node.bcrypt.js#761]
Hello
Although I reinstalled the packages and used the npm rebuild command, it still doesn't work.

 ```
Waiting for the debugger to disconnect...Error: The module '\\?\d:\yota-projects\backend\node_modules\bcrypt\lib\binding\bcrypt_lib.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1003:18)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (d:\yota-projects\backend\node_modules\bcrypt\bcrypt.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
```

**Comment by Paic** [comment]
Got the same error when building bcrypt from master (@ayZagen) or with `npm install bcrypt` (still node v12.13.0) :

```
internal/modules/cjs/loader.js:1025
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^
                 
Error: Error relocating /app/node_modules/bcrypt/lib/binding/bcrypt_lib.node: _ZN2v820EscapableHandleScope6EscapeEPPNS_8internal6ObjectE: symbol not found
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1025:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
```

**Comment by ayZagen** [comment]
@Paic  Have you tried deleting `node_modules` and installing again?

**Comment by Paic** [comment]
It's actually inside a `node:12-alpine` docker container, so `node_modules` is clean.
In either case,`bcrypt@3.0.6` or git url, bcrypt is recompiled (no download available for alpine).

**Comment by ayZagen** [comment]
I think that error is not related to bcrypt, but alpine image. Can you try using `slim` or `stretch` variants.

**Comment by Paic** [comment]
Just tested with `node:12` and got this error :

```
internal/modules/cjs/loader.js:1025
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^
Error: libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1025:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
```

I might be doing something wrong. Are you able to reproduce this ?

`Dockerfile` look as follows
```
FROM node:12

WORKDIR /app
COPY package.json ./

RUN npm install --production

COPY . .
CMD ["node", "index"]
```

**Comment by ayZagen** [comment]
It works for me. Just need to be sure, have you placed `node_modules` in your `.dockerignore` ?

**Comment by Paic** [comment]
Yes, `node_modules` is in the `.dockerignore`. I'll test that later with a clean setup.

**Comment by Paic** [comment]
Fresh `npm install bcrypt` inside a `node:12` container and a simple script works (no problem inside a `node:12-alpine`, just needs the dependencies to build `bcrypt`).
