### ISSUE TITLE
Bcrypt 3.0.7 does not install correctly on nodejs 12.13

### ISSUE THREAD

**Issue by atotalnoob** [kelektiv/node.bcrypt.js#767]
On a fresh docker image of `ubuntu 18.04` I installed nodejs `12.13.1`, then ran npm install. It seems that bcrypt can't find `v8-debug.h`. 

I've tried bcrypt versions `3.0.2` to `3.0.7` and they all fail. I also tried the latest from master.

npm log:
```
> bcrypt@3.0.7 install /app/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
[bcrypt] Success: "/app/node_modules/bcrypt/lib/binding/bcrypt_lib.node" is installed via remote

> segfault-handler@1.0.0 install /app/node_modules/segfault-handler
> node-gyp rebuild

make: Entering directory '/app/node_modules/segfault-handler/build'
  CXX(target) Release/obj.target/segfault-handler/src/segfault-handler.o
../src/segfault-handler.cpp:8:10: fatal error: v8-debug.h: No such file or directory
 #include <v8-debug.h>
          ^~~~~~~~~~~~
compilation terminated.
segfault-handler.target.mk:111: recipe for target 'Release/obj.target/segfault-handler/src/segfault-handler.o' failed
make: Leaving directory '/app/node_modules/segfault-handler/build'
make: *** [Release/obj.target/segfault-handler/src/segfault-handler.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/node_modules/segfault-handler
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
```

relevant part of the dockerfile: 
```dockerfile
FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
    postgresql-client \
    curl \
    python-dev \
    unzip \
    git \
    make \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - && \
    apt-get install -y nodejs && \
    node -v && npm -v

ENV PORT 80
EXPOSE 80

WORKDIR /app

COPY package.json /app/package.json
RUN npm install --loglevel warn
```
I also tried with 
```

RUN apt-get update && apt-get install -y \
    postgresql-client \
    curl \
    python-dev \
    unzip \
    git \
    g++ \
    gcc \
    make \
    python \
    build-essential \
    && rm -rf /var/lib/apt/lists/*
```

**Comment by atotalnoob** [comment]
It looks to me that `segfault-handler@1.0.0` is causing the issue because in `1.2` a guard is introduced that looks like it would solve this issue. I am having trouble finding the dependency path to `segfault-handler`. 

I am wondering, however, why I am the only one experiencing this issue...

**Comment by atotalnoob** [comment]
I figured it out, another dependency had `segfault-handler@1.0.0`. Once I updated that dependency, the issue went away
