### ISSUE TITLE
hash doesn't return anything

### ISSUE THREAD

**Issue by Pckool** [kelektiv/node.bcrypt.js#833]
### Problem
for some reason, bcrypt hangs when using the hash fn on my environment (both on dev and prod)
My dev environment:
- Windows 10 64x
- all prereqs/dependencies met
- bcrypt v5.0.0
- node v14.0.0
- package manager: yarn

My prod environment:
- Linux CentOS 7 64x
- all prereqs/dependencies met
- bcrypt v5.0.0
- node v12.18.4
- package manager: yarn

logs
```
1|auth-ser | [30-9-2020_23:30] -> Request accepted...
1|auth-ser | [30-9-2020_23:30] -> checking if the user exists...
1|auth-ser | [30-9-2020_23:30] -> User does not exist; Adding to db...
1|auth-ser | [30-9-2020_23:30] -> about to hash...
````
Nothing happens after this point and the request hangs

authentication.ts
```ts
export async function hashPass(pass: Password): Promise<hashObj>{
	var saltRounds = 5000;
	let id=Date.now()
	console.time('passwordHash-'+id);
	try{
		console.log("about to hash...")
		let hash: string = await bcrypt.hash(pass, saltRounds);
		console.timeLog('passwordHash-'+id); // never gotten to
		console.log("hashed successfully") // never gotten to
		return {hash};
	} catch(err){
		throw err;
	} finally{
		console.timeEnd('passwordHash-'+id);
	}
	
}
```

server.ts
```ts
app.post('/user/create', async (req: any, res: any) => {
		let user: User|null = null
		try{
			Log.info('checking if the user exists...');
			let email = req.body.username.toLowerCase();

			try{
				let existingUser = await UDB.findUser(email)
				if(existingUser) return res.status(409).json(new Error("User with that email already exists."));
			}
		        Log.info('User does not exist; Adding to db...');
			
			// if we get here, the user is not in the database
			let hashObj = await hashPass(req.body.pass);
			Log.info('Password hashed...');
                        Log.info('Generating user...');
			// if (err) throw err;
			user = {
				email,
				name: req.body.name,
				number: req.body.number,
				credentials: {
					password: hashObj.hash,
				},
				ts: Date.now(),
				id: `${Math.random().toString(36).substr(2, 9)}_${Math.random().toString(36).substr(2, 12)}`,
				namespaces: req.body.namespaces||[],
			}
			Log.info('User generated...');
			
			await UDB.add(user);

			Log.info('User added to DB...');

			res.status(200).send(`Successfully added user ${user.email}!`);
				
			Log.info(`user ${user.email} successfully generated!`);
			
		} catch(err){
			Log.error("Error when trying to create user "+JSON.stringify(user, null, 2))
			res.status(500).json(err);
		}
	});
```

I'm very confused because it was working a few days ago and now it just isn't.

### Expected Behavior
I expect it to return the function

### Workaround
N/A

[EDIT]
I found that using `async genSalt(5000)` does return a salt, but then `hashSync` throws an error saying the salt is invalid:
```
Error: Invalid salt. Salt must be in the form of: $Vers$log2(NumRounds)$saltvalue
     at Object.hashSync (/home/auth/auth-prod/source/node_modules/bcrypt/bcrypt.js:102:21)
     at Object.hashPass (/home/auth/auth-prod/source/lib/helpers/authentication.ts:49:29)
     at /home/auth/auth-prod/source/lib/server.ts:112:18
```
an example salt that is generated: `$2b$31$iQsqFjA7t7CGfyM6XPFTz`

**Comment by Pckool** [comment]
It was a misunderstanding of what the salt rounds property does. It's still very strange that the "invalid salt" error popped up even though the salt was entirely valid. *shrugs* never go over 20 saltRounds (unless you are running a threadripper/Xenon lol).

I think the naming convention should be something different though. I didn't read that part of the docs and thought the module uses that number as the real number of salt rounds, not `2^n` where `n=NumberGiven`
