### ISSUE TITLE
node-pre-gyp install --fallback-to-build not generated anything

### ISSUE THREAD

**Issue by ArkjuniorK** [kelektiv/node.bcrypt.js#869]
Hi, I was unable to install bcrypt module on server, the lib folder that required by bcrypt is not build.

* What went wrong?
I tried to install bcrypt server but node-pre-gyp the lib folder is not build and the node-pre-gyp did not gave me an error or response.
* What did you expect to happen?
lib folder should be installed
* Which version of nodejs and OS?
```
node -v  => 14.16.1
OS => GNU/Linux/CentOs 7
```
* Log/Output
```
npm info run bcrypt@5.0.1 install node_modules/bcrypt node-pre-gyp install --fallback-to-build
npm info run bcrypt@5.0.1 install { code: undefined, signal: undefined }
npm verb stack Error: spawn ENOMEM
npm verb stack     at ChildProcess.spawn (internal/child_process.js:403:11)
npm verb stack     at spawn (child_process.js:553:9)
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:36:12
npm verb stack     at new Promise (<anonymous>)
npm verb stack     at promiseSpawnUid (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:35:13)
npm verb stack     at promiseSpawn (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:15:10)
npm verb stack     at runScriptPkg (/usr/local/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script-pkg.js:66:5)
npm verb stack     at runScript (/usr/local/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script.js:9:16)
npm verb stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/rebuild.js:287:17)
npm verb stack     at run (/usr/local/lib/node_modules/npm/node_modules/promise-call-limit/index.js:30:26)
npm verb cwd /home/node/travlingv0.3/estuary_surveyor_development/estuary_surveyor_dev
npm verb Linux 3.10.0-1127.8.2.vz7.158.8
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "bcrypt" "--save" "--verbose"
npm verb node v14.16.1
npm verb npm  v7.11.1
npm ERR! code ENOMEM
npm ERR! syscall spawn
npm ERR! errno -12
npm ERR! spawn ENOMEM
npm verb exit -12
npm timing npm Completed in 4425ms
npm verb code -12
```

After update npm to v7, now I'm be able to see the error that occured but still not solve the problem about the lib folder.

**Comment by gugu** [comment]
ENOMEM is a lack of memory. What is the memory limit on the computer you use to build the module?

**Comment by ArkjuniorK** [comment]
@gugu What do you mean about the memory limit? If it's about the actual size of memory then the size is 3gb, but then half of the size is used by server to run other programs. So we only have about 1.5-1.0gb of available memory. It is the problem?

Thank you.
