### ISSUE TITLE
Error: File too short

### ISSUE THREAD

**Issue by takiuddinahmed** [kelektiv/node.bcrypt.js#878]
I am running a nodejs app on CPanel-based shared hosting that supports running nodejs application for 6 months which was running without any problem. I used nodejs version Recently found out the application not working. I checked the log and the log says error:

`
Error: /home/*******/nodevenv/******/12/lib/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node: file too short
at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
at Module.load (internal/modules/cjs/loader.js:863:32)
at Function.Module._load (internal/modules/cjs/loader.js:708:14)
at Module.require (internal/modules/cjs/loader.js:887:19)
at require (internal/modules/cjs/helpers.js:74:18)
at Object.<anonymous> (/home/outdoor1/nodevenv/prescription_server/12/lib/node_modules/bcrypt/bcrypt.js:6:16)
at Module._compile (internal/modules/cjs/loader.js:999:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
at Module.load (internal/modules/cjs/loader.js:863:32)
at Function.Module._load (internal/modules/cjs/loader.js:708:14)
internal/modules/cjs/loader.js:1057
return process.dlopen(module, path.toNamespacedPath(filename));
`

I used nodejs version 12.22.1 an bcrypt version 5.0.0.
The application is running successfully on my local pc which is running archlinux.

**Comment by recrsn** [comment]
It's probably possible that the file is corrupted on the host
