### ISSUE TITLE
Cannot install bcrypt on OpenSUSE Tumbleweed, NodeJS 14

### ISSUE THREAD

**Issue by haithngn** [kelektiv/node.bcrypt.js#908]
OpenSUSE:
```
NAME="openSUSE Tumbleweed"
# VERSION="20211222"
```
Node:
```
v14.18.2
```
NPM:
```
6.14.15
```

Compiler: (https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions#alpine-linux-based-images)
```
gcc-c++
make
```

## Problem:
out from cmd: npm install bcrypt
```
npm WARN deprecated bcrypt@3.0.8: versions < v5.0.0 do not handle NUL in passwords properly
npm WARN deprecated node-pre-gyp@0.14.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future

> bcrypt@3.0.8 install /home/current_user/workspace/repositories/be_code/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.8/bcrypt_lib-v3.0.8-node-v83-linux-x64-glibc.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for bcrypt@3.0.8 and node@14.18.2 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
gyp: /usr/include/node14/common.gypi not found (cwd: /home/current_user/workspace/repositories/be_code/node_modules/bcrypt) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib64/node_modules/npm14/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Linux 5.15.8-1-default
gyp ERR! command "/usr/bin/node14" "/usr/lib64/node_modules/npm14/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/current_user/workspace/repositories/be_code/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/home/current_user/workspace/repositories/be_code/node_modules/bcrypt/lib/binding" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /home/current_user/workspace/repositories/be_code/node_modules/bcrypt
gyp ERR! node -v v14.18.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node14 /usr/lib64/node_modules/npm14/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/current_user/workspace/repositories/be_code/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/home/current_user/workspace/repositories/be_code/node_modules/bcrypt/lib/binding --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/current_user/workspace/repositories/be_code/node_modules/bcrypt/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1058:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
node-pre-gyp ERR! System Linux 5.15.8-1-default
node-pre-gyp ERR! command "/usr/bin/node14" "/home/current_user/workspace/repositories/be_code/node_modules/bcrypt/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/current_user/workspace/repositories/be_code/node_modules/bcrypt
node-pre-gyp ERR! node -v v14.18.2
node-pre-gyp ERR! node-pre-gyp -v v0.14.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node14 /usr/lib64/node_modules/npm14/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/current_user/workspace/repositories/be_code/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/home/current_user/workspace/repositories/be_code/node_modules/bcrypt/lib/binding --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm WARN swagger-stats@0.95.19 requires a peer of prom-client@>= 10 <= 12 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@3.0.8 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@3.0.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/current_user/.npm/_logs/2021-12-25T06_14_06_176Z-debug.log

```

Could you please give any advice, thank you for taking a look at this issue.

**Comment by recrsn** [comment]
3.0.8 is outdated, update to 5.0.1
