### ISSUE TITLE
NPM fails on msbuild.exe with exit code 1

### ISSUE THREAD

**Issue by gilbertbw** [kelektiv/node.bcrypt.js#94]
from: https://github.com/TooTallNate/node-gyp/issues/119

Cmd output:

```
c:\Users\Gilbert\WebstormProjects\NodeOfGames\node_modules\bcrypt>node "C:\Progr
am Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node
-gyp\bin\node-gyp.js" rebuild
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppBuild.targets(29
7,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.
  TargetFrameworkVersion or PlatformToolset may be set to an invalid version nu
mber. [c:\Users\Gilbert\WebstormProjects\NodeOfGames\node_modules\bcrypt\build\
bcrypt_lib.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\Win32\Microsoft.Cpp
.Win32.Targets(147,5): error MSB6006: "CL.exe" exited with code -1073741515. [c
:\Users\Gilbert\WebstormProjects\NodeOfGames\node_modules\bcrypt\build\bcrypt_l
ib.vcxproj]
gyp ERR! rebuild error Error: `C:\windows\Microsoft.NET\Framework\v4.0.30319\msb
uild.exe` failed with exit code: 1
gyp ERR! rebuild error     at ChildProcess.onExit (C:\Program Files (x86)\nodejs
\node_modules\npm\node_modules\node-gyp\lib\build.js:214:23)
gyp ERR! rebuild error     at ChildProcess.EventEmitter.emit (events.js:91:17)
gyp ERR! rebuild error     at Process._handle.onexit (child_process.js:674:10)
gyp ERR! not ok
npm ERR! bcrypt@0.7.1 install: `node-gyp rebuild`
npm ERR! `cmd "/c" "node-gyp rebuild"` failed with 1
npm ERR!
npm ERR! Failed at the bcrypt@0.7.1 install script.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program File
s (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "bcrypt" "--save"

npm ERR! cwd c:\Users\Gilbert\WebstormProjects\NodeOfGames
npm ERR! node -v v0.8.1
npm ERR! npm -v 1.1.33
npm ERR! code ELIFECYCLE
npm ERR! message bcrypt@0.7.1 install: `node-gyp rebuild`
npm ERR! message `cmd "/c" "node-gyp rebuild"` failed with 1
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     c:\Users\Gilbert\WebstormProjects\NodeOfGames\npm-debug.log
npm ERR! not ok code 0

c:\Users\Gilbert\WebstormProjects\NodeOfGames>npm install bcrypt --save
npm http GET https://registry.npmjs.org/bcrypt
npm http 304 https://registry.npmjs.org/bcrypt
npm http GET https://registry.npmjs.org/bindings/1.0.0
npm http 304 https://registry.npmjs.org/bindings/1.0.0

> bcrypt@0.7.1 install c:\Users\Gilbert\WebstormProjects\NodeOfGames\node_module
s\bcrypt
> node-gyp rebuild


c:\Users\Gilbert\WebstormProjects\NodeOfGames\node_modules\bcrypt>node "C:\Progr
am Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node
-gyp\bin\node-gyp.js" rebuild
  blowfish.cc
  bcrypt.cc
  bcrypt_node.cc
c:\users\gilbert\.node-gyp\0.8.1\src\node_object_wrap.h(57): warning C4251: 'no
de::ObjectWrap::handle_' : class 'v8::Persistent<T>' needs to have dll-interfac
e to be used by clients of class 'node::ObjectWrap' [c:\Users\Gilbert\WebstormP
rojects\NodeOfGames\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
          with
          [
              T=v8::Object
          ]
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\xlocale(323): wa
rning C4530: C++ exception handler used, but unwind semantics are not enabled.
Specify /EHsc [c:\Users\Gilbert\WebstormProjects\NodeOfGames\node_modules\bcryp
t\build\bcrypt_lib.vcxproj]
c:\users\gilbert\.node-gyp\0.8.1\deps\openssl\openssl\include\openssl\../../e_o
s2.h(56): fatal error C1083: Cannot open include file: 'openssl/opensslconf.h':
 No such file or directory [c:\Users\Gilbert\WebstormProjects\NodeOfGames\node_
modules\bcrypt\build\bcrypt_lib.vcxproj]
gyp ERR! rebuild error Error: `C:\windows\Microsoft.NET\Framework\v4.0.30319\msb
uild.exe` failed with exit code: 1
gyp ERR! rebuild error     at ChildProcess.onExit (C:\Program Files (x86)\nodejs
\node_modules\npm\node_modules\node-gyp\lib\build.js:214:23)
gyp ERR! rebuild error     at ChildProcess.EventEmitter.emit (events.js:91:17)
gyp ERR! rebuild error     at Process._handle.onexit (child_process.js:674:10)
gyp ERR! not ok
npm ERR! bcrypt@0.7.1 install: `node-gyp rebuild`
npm ERR! `cmd "/c" "node-gyp rebuild"` failed with 1
npm ERR!
npm ERR! Failed at the bcrypt@0.7.1 install script.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program File
s (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "bcrypt" "--save"

npm ERR! cwd c:\Users\Gilbert\WebstormProjects\NodeOfGames
npm ERR! node -v v0.8.1
npm ERR! npm -v 1.1.33
npm ERR! code ELIFECYCLE
npm ERR! message bcrypt@0.7.1 install: `node-gyp rebuild`
npm ERR! message `cmd "/c" "node-gyp rebuild"` failed with 1
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     c:\Users\Gilbert\WebstormProjects\NodeOfGames\npm-debug.log
npm ERR! not ok code 0
```

**Comment by dylanh724** [comment]
It's more than just not having visual studio installed -- don't you know that C++ is NOT INSTALLED BY DEFAULT with visual studio? You have to specifically browse through and check it. You should very much specify this ;)
